---
    - name: "intall pip3"
      apt:
        name: python3-pip
        update_cache: yes

    - name: "install docker"
      pip:
        name: docker

    - name: "Create dir for prometheus"
      file:
        path: "{{ prometheus_home }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x

    - name: "Create dir for grafana"
      file:
        path: "{{ grafana_home }}/{{ item }}"
        state: directory
        owner: 472
        group: 472
        mode: u=rwx,g=x,o=x
      with_items:
        - data
        - log
        - config
        - plugins

    - name: "Copy config prometheus"
      template:
        src=templates/prometheus.yml
        dest="{{ prometheus_home }}"

    - name: "Copy config grafana"
      template:
        src=templates/custom.ini
        dest="{{ grafana_home }}/config"

    - name: "Copy config provision grafana"
          template:
            src=templates/grafana_provision.yml
            dest="{{ grafana_home }}/config"

    - name: "Start grafana docker"
      docker_container:
       name: grafana
       image: grafana/grafana
       ports:
        - 3000:3000
       volumes:
        - "{{ grafana_home }}/data:/var/lib/grafana"
        - "{{ grafana_home }}/log:/var/log/grafana"
        - "{{ grafana_home }}/config/custom.ini:/etc/grafana/grafana.ini"
        - "{{ grafana_home }}/config/grafana_provision.yml:/etc/grafana/provisioning/datasources/prometheus.yml"
       recreate: yes

    - name: "Start alertmanager docker"
      docker_container:
       name: alertmanager
       image: prom/alertmanager
       ports:
        - 9093:9093
       recreate: yes

    - name: "Start prometheus docker"
      docker_container:
       name: prometheus
       image: prom/prometheus
       ports:
        - 9090:9090
       volumes:
        - "{{ prometheus_home }}/prometheus.yml:/etc/prometheus/prometheus.yml"
       recreate: yes