---
    - name: "Install nginx/pip3"
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - nginx
        - python3-pip

    - name: "Install docker"
      pip:
        name: docker

    - name: "Copy nginx.conf"
      template:
        src=templates/nginx.conf
        dest=/etc/nginx/nginx.conf

    - name: "Restart nginx"
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: "Create dir for wordpress"
      file:
        path: "{{ wordpress_data }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x

    - name: "install docker Wordpress"
      docker_container:
       name: wordpress
       image: wordpress
       env:
         WORDPRESS_DB_HOST: localhost
         WORDPRESS_DB_USER: "{{ db_user }}"
         WORDPRESS_DB_PASSWORD: "{{ db_pass }}"
         WORDPRESS_DB_NAME: "{{ db_name }}"
         WORDPRESS_CONFIG_EXTRA: |
          define('DOMAIN_CURRENT_SITE', 'pandamys.ru');
          define('WP_SITEURL', 'http://pandamys.ru');
          define('WP_HOME', 'http://pandamys.ru');
       ports:
        - 8080:80
       volumes:
        - "{{ wordpress_data }}:/var/www/html"
       recreate: yes