---
    - name: "Install nginx"
      apt:
        name: nginx
        update_cache: yes

    - name: "install docker Wordpress"
      docker_container:
       name: wordpress
       image: wordpress
       env:
         WORDPRESS_DB_HOST: {{ hostvars['mysql-db01']['ansible_default_ipv4']['address'] }}
         WORDPRESS_DB_USER: {{ db_user }}
         WORDPRESS_DB_PASSWORD: {{ db_pass }}
         WORDPRESS_DB_NAME: {{ db_name }}