---
    - name: "Install nginx/pip3"
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - nginx
        - python3-pip

    - name: "Install docker"
      pip:
        name: docker

    - name: "install docker Wordpress"
      docker_container:
       name: wordpress
       image: wordpress
       env:
         WORDPRESS_DB_HOST: "192.168.10.34"
         WORDPRESS_DB_USER: "{{ db_user }}"
         WORDPRESS_DB_PASSWORD: "{{ db_pass }}"
         WORDPRESS_DB_NAME: "{{ db_name }}"
         WORDPRESS_CONFIG_EXTRA: |
          define('DOMAIN_CURRENT_SITE', 'pandamys.ru');

       ports:
        - 8080:80