---
    webservers:
      hosts:
        nginx:
          ansible_host: 62.84.115.167

    databases:
      hosts:
        mysql-db01:
          ansible_host: 62.84.115.239
        mysql-db02:
          ansible_host: 51.250.93.154

    wordpress:
      hosts:
        app-01:
          ansible_host: 62.84.115.59

    monitoring:
      hosts:
        ansible_host: 62.84.115.59