---
    webservers:
      hosts:
        nginx:
          ansible_host: 51.250.76.41

    databases:
      hosts:
        mysql-db01:
          ansible_host: 51.250.83.204
        mysql-db02:
          ansible_host: 51.250.79.159

    wordpress:
      hosts:
        app:
          ansible_host: 51.250.90.74