---
    - name: update apt packages
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: install pip3
      apt:
        name=python3-pip
        state=latest
      when: ansible_os_family == "Debian"

    - name: install docker
      pip:
        name: docker

    - name: "Create dir for config"
      file:
        path: "{{ mysql_config }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x

    - name: "Copy config my.cnf"
      template:
        src=templates/my.cnf
        dest="{{ mysql_config }}"

    - name: "Copy config mysql-cluster.cnf"
      template:
        src=templates/mysql-cluster.cnf
        dest="{{ mysql_config }}"

    - name: create docker network
      docker_network:
        name: "{{ docker_network_name }}"
        driver: "ipvlan"
        ipam_config:
          - subnet: '192.168.0.0/16'
            gateway: '192.168.0.1'

    - name: install cluster container
      docker_container:
        name: management1
        image: mysql/mysql-cluster
        state: started
        detach: yes
        ports:
          - "3306:3306"
        networks:
          - name: "{{ docker_network_name }}"
            ipv4_address: "{{ mysql_address_managment }}"
        command: ndb_mgmd
        volumes:
          - /etc/config_mysql/my.cnf:/etc/my.cnf
          - /etc/config_mysql/my.cnf:/etc/mysql-cluster.cnf
      when: inventory_hostname == "mysql-db01"

    - name: install docker container mysql
      docker_container:
        name: mysql
        image: mysql/mysql-cluster
        state: started
        auto_remove: true
        detach: yes
        ports:
          - "3301:3306"
        env:
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_pass }}"
          MYSQL_DATABASE: "{{ db_name }}"
          MYSQL_RANDOM_ROOT_PASSWORD: "true"
        networks:
          - name: "{{ docker_network_name }}"
            ipv4_address: "{{ lookup('vars', 'docker_address_' ~ inventory_hostname) }}"
        volumes:
          - /etc/config_mysql/my.cnf:/etc/my.cnf
          - /etc/config_mysql/my.cnf:/etc/mysql-cluster.cnf
        command: ndbd

    - name: install container server node
      docker_container:
        name: mysql1
        image: mysql/mysql-cluster
        state: started
        detach: yes
        ports:
          - "3302:3306"
        networks:
          - name: "{{ docker_network_name }}"
            ipv4_address: "{{ mysql_address_server_node }}"
        volumes:
          - /etc/config_mysql/my.cnf:/etc/my.cnf
          - /etc/config_mysql/my.cnf:/etc/mysql-cluster.cnf
        command: mysqld
      when: inventory_hostname == "mysql-db01"