---
    - name: update apt packages
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "upload mysql"
      get_url:
        url: "https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-management-server_{{ mysql_version }}-1ubuntu18.04_amd64.deb"
        dest: "/tmp/mysql-{{ mysql_version }}-linux-x86_64.deb
        mode: 0755
        timeout: 60
        force: true
        validate_certs: false
      register: get_mysql
      until: get_mysql is succeeded
      tags: mysql

    - name: "Install mysql"
      apt:
        deb: "/tmp/mysql-{{ mysql_version }}-linux-x86_64.deb"

    - name: "Create dir for cluster"
      file:
        path: "{{ mysql_cluster_dir }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x

    - name: "Copy config mysql_cluster.cnf"
      template:
        src=templates/mysql_cluster.cnf
        dest="{{ mysql_cluster_dir }}/config.ini"

    - name: copy ndb_mgmd.service file
      copy:
        src: ndb_mgmd.service
        dest: /etc/systemd/system/ndb_mgmd.service

    - name: reload daemon
      shell: systemctl daemon-reload

    - name: Initialize ndb_mgmd
      service:
        name: ndb_mgmd
        state: started
