worker_processes: auto
worker_connections: 2048
client_max_body_size: 512M
wordpress_address: "{{ hostvars['app-01']['ansible_default_ipv4']['address'] }}"
gitlab_address: "{{ hostvars['gitlab']['ansible_default_ipv4']['address'] }}"
grafana_address: "{{ hostvars['grafana']['ansible_default_ipv4']['address'] }}"
prometheus_address: "{{ hostvars['grafana']['ansible_default_ipv4']['address'] }}"
alertmanager_address: "{{ hostvars['grafana']['ansible_default_ipv4']['address'] }}"

acme_challenge_type: http-01
acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
acme_version: 2
acme_email: gruver2007@ya.ru
letsencrypt_dir: /etc/letsencrypt
letsencrypt_keys_dir: /etc/letsencrypt/keys
letsencrypt_csrs_dir: /etc/letsencrypt/csrs
letsencrypt_certs_dir: /etc/letsencrypt/certs
letsencrypt_account_key: /etc/letsencrypt/account/account.key
domain_name: pandamys.ru