---
    - name: Install Nginx Web Server on Debian Family
      apt:
        name=nginx
        state=latest
      when:
        ansible_os_family == "Debian"
      notify:
        - nginx systemd

    - name: Install Nginx Web Server on RedHat Family
      yum:
        name=nginx
        state=latest
      when:
        ansible_os_family == "RedHat"
      notify:
        - nginx systemd

    - name: Replace nginx.conf
      template:
        src=templates/nginx.conf
        dest=/etc/nginx/nginx.conf

    - name: Add virtual domain in NGINX
      template:
        src=templates/nginx_vhosts.conf
        dest=/etc/nginx/conf.d/vhosts.conf