---
    - name: "Install monitoring"
      hosts: monitoring
      become: yes
      roles:
        - monitoring
        - node_exporter

    #- name: "Install nginx-proxy"
    #  hosts: webservers
    #  become: yes
    #  roles:
    #    - nginx
    #    - node_exporter