---
    - name: "Install mysql"
      hosts: databases
      become: yes
      roles:
        - mysql
        - node_exporter

    - name: "Install wordpress"
      hosts: wordpress
      become: yes
      roles:
        - wordpress

    - name: "Install CI"
      hosts: ci
      become: yes
      roles:
        - gitlab

    - name: "Install monitoring"
      hosts: monitoring
      become: yes
      roles:
        - monitoring

    - name: "Install nginx-proxy"
      hosts: webservers
      become: yes
      roles:
        - nginx