---
    - name "get all info"
      setup:
        delegate_to: {{ item }}
        delegate_facts: True
      with_items: "{{ groups['all'] }}"

    - name: "Install nginx"
      hosts: webservers
      become: yes
      roles:
        - nginx

    - name: "Install mysql"
      hosts: databases
      become: yes
      roles:
        - mysql

    - name: "Install wordpress"
      hosts: wordpress
      become: yes
      roles:
        - wordpress