---
    - name: "intall pip3"
      apt:
        name: python3-pip
        update_cache: yes

    - name: "install docker"
      pip:
        name: docker

    - name: "Create dir for gitlab"
      file:
        path: "{{ gitlab_home }}/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x
      with_items:
        - data
        - logs
        - config

    - name: "Create dir for gitlab-runner"
      file:
        path: "{{ gitlab_runner_home }}/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x
      with_items:
        - data
        - config

    - name: "Copy config gitlab"
      template:
        src=templates/gitlab.rb
        dest="{{ gitlab_home }}/config"

    - name: "Start gitlab docker"
      docker_container:
       name: gitlab
       image: gitlab/gitlab-ce:latest
       #env:
        #GITLAB_OMNIBUS_CONFIG: |
          # external_url "https://{{ gitlab_domain }}"
          # Add any other gitlab.rb configuration here, each on its own line
       ports:
        - "8080:80"
        - "2224:22"
       volumes:
        - "{{ gitlab_home }}/data:/var/opt/gitlab"
        - "{{ gitlab_home }}/logs:/var/log/gitlab"
        - "{{ gitlab_home }}/config:/etc/gitlab"
       recreate: yes

    - name: "Start gitlab-runner docker"
      docker_container:
       name: gitlab-runner
       image: gitlab/gitlab-runner:latest
       volumes:
        - "{{ gitlab_runner_home }}/data:/home/gitlab_ci_multi_runner/data"
        - "{{ gitlab_runner_home }}/config:/etc/gitlab-runner"
        - "/var/run/docker.sock:/var/run/docker.sock:rw"
       env:
        CI_SERVER_URL: "https://{{ gitlab_domain }}/ci"
       recreate: yes